In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from collections import OrderedDict
import re
import dgl
from torch.utils.data import DataLoader
import math 
import torch.nn.functional as F
import dgl.function as fn
from dgl.nn.functional import edge_softmax

F:\anaconda\envs\wppenv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
Thunderbird_log = pd.read_csv(r"G:\wpp\dataset and paper\Transfer-HGT\data-process\Thunderbird\Thunderbird_log_structured.csv",memory_map=True)
Thunderbird_log.head()

,LineId,Label,Timestamp,Date,User,Month,Day,Time,Location,Component,PID,Content,EventId,EventTemplate,ParameterList,Key
0,600001,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
1,600002,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
2,600003,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
3,600004,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
4,600005,"""VAPI",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367

In [3]:
Thunderbird_log['Content'][0],Thunderbird_log['EventTemplate'][0]

('THH(1): mnt_projects/sysapps/src/ib/topspin/topspin-src-3.2.0-16/third_party/thca4_linux/kernel/mlxhh/thh/obj_host_amd64_custom1_rhel4/mod_thh/hob_comm.c[1597]: XHH_hob_process_local_mad: Device in FATAL state',
 'THH(1): <*> <*> Device in FATAL state')

In [4]:
BGL_Log_Structured = pd.read_csv(r"G:\wpp\dataset and paper\Transfer-HGT\data\BGL\BGL_Log_Structured.csv",memory_map=True)
BGL_Log_Structured.head()

,LineId,Label,Timestamp,Date,Node,Time,NodeRepeat,Type,Component,Level,Content,EventId,EventTemplate,ParameterList
0,1,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.363779,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected,[]
1,2,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.527847,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected,[]
2,3,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.675872,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected,[]
3,4,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.823719,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected,[]
4,5,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.982731,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected,[]

In [7]:
BGL_Log_Structured['Content'][10000],BGL_Log_Structured['EventTemplate'][10000]

('generating core.1038', 'generating <*>')

In [3]:
Thunderbird_log

,LineId,Label,Timestamp,Date,User,Month,Day,Time,Location,Component,PID,Content,EventId,EventTemplate,ParameterList,Key
0,600001,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
1,600002,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
2,600003,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
3,600004,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
4,600005,"""VAPI",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,kernel,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399526,999527,"""-",1131963039,2005.11.14,an933,Nov,14,02:10:39,an933/an933,kernel,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
399527,999528,"""VAPI",1131963039,2005.11.14,an933,Nov,14,02:10:39,an933/an933,kernel,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
399528,999529,"""VAPI",1131963039,2005.11.14,an933,Nov,14,02:10:39,an933/an933,kernel,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
399529,999530,"""-",1131963039,2005.11.14,dn30,Nov,14,02:10:39,dn30/dn30,kernel,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
399530,999531,"""VAPI",1131963039,2005.11.14,dn30,Nov,14,02:10:39,dn30/dn30,kernel,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367

In [4]:
'''
存在不同组件，相同的日志事件   的情况
'''
com = Thunderbird_log['Component'].unique()
com_id=np.array([x for x in range(1,55) ])
com_dict = dict(zip(com,com_id))
# com_dict
# for index,row in Thunderbird_log.iterrows():
#     if row['Component']=='portmap':
#         print(row)

In [5]:
for i in com_dict.keys():
    com_dict[i] = "C"+str(com_dict[i])
com_dict

{'kernel': 'C1',
 'ntpd': 'C2',
 'ib_sm.x': 'C3',
 '/apps/x86_64/system/ganglia-3.0.1/sbin/gmetad': 'C4',
 'Server Administrator': 'C5',
 'snmpd': 'C6',
 'syslog-ng': 'C7',
 'crond(pam_unix)': 'C8',
 'crond': 'C9',
 'dhcpd': 'C10',
 'xinetd': 'C11',
 'sendmail': 'C12',
 'pam_limits': 'C13',
 'irqbalance': 'C14',
 'syslog': 'C15',
 'syslogd 1.4.1': 'C16',
 'nfslock': 'C17',
 'portmap': 'C18',
 'rc': 'C19',
 'rpc.statd': 'C20',
 'rpcidmapd': 'C21',
 'ts_fixup': 'C22',
 'netfs': 'C23',
 'acpid': 'C24',
 'date': 'C25',
 'fsck': 'C26',
 'init': 'C27',
 'lvm.static': 'C28',
 'mount.panfs': 'C29',
 'mount': 'C30',
 'network': 'C31',
 'rc.sysinit': 'C32',
 'smartd': 'C33',
 'start_udev': 'C34',
 'sysctl': 'C35',
 'udevsend': 'C36',
 'instsvcdrv': 'C37',
 'dataeng': 'C38',
 'sshd': 'C39',
 'gmond': 'C40',
 'ntpdate': 'C41',
 'pbs_mom': 'C42',
 'messagebus': 'C43',
 'omsad': 'C44',
 'fstab-sync': 'C45',
 'haldaemon': 'C46',
 'sudo': 'C47',
 'logger': 'C48',
 'userhelper': 'C49',
 'sshd(pam_unix)': 'C50',
 'in.tftpd': 'C51',
 'postfix/postdrop': 'C52',
 'sshd2': 'C53',
 'syslogd': 'C54'}

In [6]:
Thunderbird_log['Component'] = Thunderbird_log['Component'].apply( lambda x: com_dict[x])
Thunderbird_log

,LineId,Label,Timestamp,Date,User,Month,Day,Time,Location,Component,PID,Content,EventId,EventTemplate,ParameterList,Key
0,600001,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
1,600002,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
2,600003,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
3,600004,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
4,600005,"""VAPI",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399526,999527,"""-",1131963039,2005.11.14,an933,Nov,14,02:10:39,an933/an933,C1,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
399527,999528,"""VAPI",1131963039,2005.11.14,an933,Nov,14,02:10:39,an933/an933,C1,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
399528,999529,"""VAPI",1131963039,2005.11.14,an933,Nov,14,02:10:39,an933/an933,C1,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
399529,999530,"""-",1131963039,2005.11.14,dn30,Nov,14,02:10:39,dn30/dn30,C1,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
399530,999531,"""VAPI",1131963039,2005.11.14,dn30,Nov,14,02:10:39,dn30/dn30,C1,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367

In [7]:
Event = Thunderbird_log.drop_duplicates(subset='EventId',inplace=False)
Event

,LineId,Label,Timestamp,Date,User,Month,Day,Time,Location,Component,PID,Content,EventId,EventTemplate,ParameterList,Key
0,600001,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
2,600003,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
4,600005,"""VAPI",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
10,600011,"""-",1131904443,2005.11.13,dn25,Nov,13,09:54:03,dn25/dn25,C2,2260.0,"synchronized to 10.100.28.250, stratum 3""",ef226888,synchronized to <*> stratum <*>,"['10.100.28.250,', '3""']",E44
24,600025,-,1131904444,2005.11.13,tbird-sm1,Nov,13,09:54:04,src@tbird-sm1,C3,24904.0,[INFO]: Configuration caused by some ports in ...,5d37b30c,[INFO]: Configuration caused by some ports in ...,[],E375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315666,915667,-,1131951605,2005.11.13,bn575,Nov,13,23:00:05,bn575/bn575,C26,NaN,[/sbin/fsck.ext3 (1) -- /var],24bc2b8c,[/sbin/fsck.ext3 (1) -- <*>,['/var]'],E407
315667,915668,-,1131951605,2005.11.13,bn575,Nov,13,23:00:05,bn575/bn575,C26,NaN,fsck.ext3 -a /dev/sda5,f5db9ad3,fsck.ext3 -a <*>,['/dev/sda5'],E408
331143,931144,-,1131953731,2005.11.13,bn575,Nov,13,23:35:31,bn575/bn575,C25,NaN,Mon Nov 14 00:35:16 MST 2005,b5547c6f,Mon Nov 14 <*> MST 2005,['00:35:16'],E14
336911,936912,-,1131954540,2005.11.13,#1#,Nov,13,23:49:00,#1#/#1#,C1,NaN,audit(1131950940.033:0): avc: denied { search ...,27c493db,audit(<*><*>): avc: denied { search } for pid<...,"['1131950940.033:0', '=19258', '=30 scontext=u...",E402
342537,942538,-,1131955321,2005.11.14,#21#,Nov,14,00:02:01,#21#/#21#,C9,26273.0,(#65#) CMD (/home/#65#/salinas/tbird/cron_scri...,f9423625,(#65#) CMD (/home/#65#/salinas/tbird/cron_scri...,[],E477

In [8]:
com_dict
for i in com_dict.values(): 
    print(i)

C1
C2
C3
C4
C5
C6
C7
C8
C9
C10
C11
C12
C13
C14
C15
C16
C17
C18
C19
C20
C21
C22
C23
C24
C25
C26
C27
C28
C29
C30
C31
C32
C33
C34
C35
C36
C37
C38
C39
C40
C41
C42
C43
C44
C45
C46
C47
C48
C49
C50
C51
C52
C53
C54

In [9]:
com_Event_dict = OrderedDict()
for i in com_dict.values(): 
    if i not in com_Event_dict:
        com_Event_dict[i] = []
for index,row in  Thunderbird_log.iterrows():
    if row['EventId'] not in com_Event_dict[row['Component']]:
        com_Event_dict[row['Component']].append(row['EventId'])
com_Event_dict

OrderedDict([('C1',
              ['f29fb486',
               'afa7654c',
               '4f5b9781',
               '45d319cb',
               'a1cbc82b',
               'a20abb3d',
               '6dc36b09',
               'b6bf46de',
               '0f5f997d',
               'a4ff4c6f',
               'f69dda74',
               'ad416b7e',
               'af614352',
               '87cf408f',
               '71357687',
               '115635d6',
               '295c8236',
               '6204d307',
               '8c537990',
               'f3baae88',
               '7e2eac94',
               'de6cd9cf',
               '6d58ac7e',
               'c36d1d3d',
               '1d743fc4',
               '7d2f04f5',
               'cc2cb575',
               'c1a59557',
               '5f45a05e',
               'cd56675f',
               '2fec979e',
               'ab8e12aa',
               '1cf019dc',
               'e727dd7e',
               'f0988321',
               '1ce35610',
               'befec666',
               '5af5972d',
               'cb918ea9',
               '21e60650',
               '6dae5f8b',
               'a6c81dd8',
               '4b27a725',
               '393e6aaa',
               '158c34d8',
               '426f668c',
               '7e9e0987',
               '40014f29',
               'be631275',
               'cd364792',
               '4018d47d',
               'f05494ed',
               '41ffccb1',
               'f7dc852a',
               '2393c4e5',
               'c548107e',
               '226c1616',
               'eda996fc',
               '2a1f7496',
               '4c266658',
               'dc008d73',
               '503eca1e',
               '5f59c0fe',
               '61080331',
               '1d6c9690',
               'b218fa4c',
               'da8564c1',
               '3c9bd707',
               '0ccf363e',
               '0ba4f522',
               '154e9fae',
               'b1ecff3c',
               '2d9fabff',
               '0278a557',
               '06825620',
               '8f43df13',
               '4e856061',
               'aebadbc0',
               'cc6328c4',
               '8f61471d',
               '83fe54c5',
               'e29b6981',
               '679e773a',
               'edb20730',
               'a090a511',
               'aff64990',
               '7c4a740d',
               '56824959',
               '415ce39a',
               'f70a10ee',
               '09cd9ade',
               'bdb7ce49',
               '707f0b33',
               'e6f56863',
               '6df6ed98',
               '91e8ab9e',
               '2b566107',
               '3637fd61',
               '02604bb0',
               'd8cdb7cf',
               '50e8fc89',
               '634ae816',
               '4347d6c6',
               '4af88f8f',
               '8d630a2b',
               'f0a878f0',
               'f73595e3',
               '41ed2983',
               '02b10438',
               '4aacee6a',
               '657892af',
               '607eef3d',
               '53f8734e',
               '204ba6f2',
               'b0ef9ace',
               '13c67684',
               '208b1922',
               'cecc13aa',
               'ebb6db13',
               'ee2ae22f',
               '96420960',
               '892c3001',
               '00bc9d8a',
               'bf263f16',
               'a3c4dedb',
               '4768ff86',
               '11e22d59',
               'a3bd2f17',
               '7ccebfbe',
               '866670b9',
               'dbcb1718',
               'cb45fbbf',
               '65e052ed',
               '4b7e6959',
               '6550622f',
               '521066c3',
               'e8438cc2',
               '88474e9c',
               '385a86d9',
               'fe847c07',
               '975383bf',
               '6e3475e7',
               '14d68ea0',
               'e24fae92',
               '3cea1e5a',
               '92398283',
               'ef476468',
               'fe1ca4c4',
               'ed2d7b9b',
               '5ab7d0e6',
               'a166300a',
               '756b90dd',
               'b79529df',
               'eb9b1482',
               '204c3170',
               '14adadc3',
               'cb46a609',
               '71372c58',
               '38fe4fa3',
               'b5e84bfb',
               '323c0b75',
               '69ea804c',
               '3b85d690',
               '337ed584',
               '5de8e064',
               '28d86c57',
               '16f3e1f5',
               'e80c8a5c',
               '2d63468e',
               '9cce776b',
               '8f4c17d6',
               'd7c85960',
               '1c5e39cb',
               '7238147a',
               '90ea87d9',
               'ed48f744',
               '519a6e46',
               '2526593d',
               '69092dfc',
               '72fc5a1c',
               'e8c5a3ff',
               'e2c5eb70',
               '30d35175',
               'f1205e3c',
               '14930dc8',
               '26096bac',
               '1da5319d',
               'b4a1b6c7',
               'f0c4672c',
               '26e04130',
               '7b1c71f5',
               '9e04d0e1',
               '9e54b051',
               '372e7234',
               'b422c811',
               '42d059a0',
               '23c2de50',
               'd4273323',
               'cd25cf18',
               '81311be0',
               'd3809c1a',
               'db3a1891',
               'c6a2d330',
               '23684e20',
               'c49e7242',
               '27c493db']),
             ('C2',
              ['ef226888',
               '9b1751bd',
               '713e618e',
               '09487f02',
               '12c0517e',
               '99132f5d',
               '14b78a6b',
               '5ba16b80',
               '55ab9c77',
               'b7307c84',
               'd313251e',
               'fad40d5e']),
             ('C3',
              ['5d37b30c',
               '8e6e114b',
               '7861dafa',
               '51a56721',
               '0170c871',
               'b523b147',
               'a0939195',
               '8d134961',
               '1d72dbe7',
               '436ae99e',
               'a0464834',
               'f67f0ac3',
               '31d3084a',
               'cc6bd0df',
               '12e96422']),
             ('C4', ['6391d957', 'b1402c3a', 'c28f47dc']),
             ('C5', ['7af5f6c5', '5b2bcc81', 'a69485db', '54ffff38']),
             ('C6',
              ['5f6a681c',
               '2315719c',
               '3780647e',
               '09d8601c',
               'ff0546a4',
               '4d20657c']),
             ('C7', ['50345058']),
             ('C8', ['09789b2b', '27624832']),
             ('C9', ['5947eee3', '2315719c', 'd6087b0c', 'f9423625']),
             ('C10',
              ['f4455acc',
               'd0052946',
               '3b327ac5',
               'a82970ae',
               'e8b0f746',
               'fe7d0745',
               'c7ce01a8']),
             ('C11',
              ['f8c00723',
               '2315719c',
               '73032e3b',
               '9eb8e3c7',
               '49f6bba5',
               '6208f537']),
             ('C12', ['182a3d2f', 'fadd4d28', '99659397', 'bc4872ea']),
             ('C13', ['910e288d', 'b10a98bd']),
             ('C14', ['2315719c']),
             ('C15', ['abd14c95', '2315719c', '47adbf55']),
             ('C16', ['6f97e9d4']),
             ('C17', ['2315719c']),
             ('C18', ['2315719c']),
             ('C19', ['ea2ebcf2']),
             ('C20', ['268e6e9a']),
             ('C21', ['2315719c']),
             ('C22', ['1a2ac521']),
             ('C23', ['144d91a4']),
             ('C24', ['2315719c']),
             ('C25', ['9efabb2d', 'b5547c6f']),
             ('C26',
              ['8bf43913',
               '3eb304b6',
               '696dbc03',
               '3a7c1c2f',
               '24bc2b8c',
               'f5db9ad3']),
             ('C27', ['68afa78e']),
             ('C28', ['cb918ea9']),
             ('C29', ['0bd88115', 'b95b0ee2', 'e88b3270']),
             ('C30', ['0bd88115', '8f9476cd', '0fb7ec34', '5bca1be3']),
             ('C31', ['f9edea77', 'a84c7411']),
             ('C32',
              ['5067ee0f',
               'ea0f0cf9',
               'f68465f1',
               'ce6689c4',
               '7cffd2ab',
               '50d5309e',
               '144d91a4',
               'f7aa7a98',
               '438072cf',
               'a84c7411',
               'b533c717']),
             ('C33',
              ['337ec120',
               '3adcc40c',
               '143fc45a',
               'a4657e66',
               '3e5fb2d5',
               '3425827a',
               'bacffe20',
               'b73df3e2',
               '684602dc',
               '3e37be4e']),
             ('C34', ['ea2ebcf2']),
             ('C35',
              ['34111b96',
               '172d92d2',
               'd7b61992',
               '5bba403d',
               'dc4a9fc8',
               '87d982c0',
               '7eccf143',
               '87c67553',
               'af74229d',
               'beb2ace4']),
             ('C36', ['22a97846']),
             ('C37', ['04b50848', 'ed4394f9']),
             ('C38', ['2315719c']),
             ('C39',
              ['9b1751bd',
               'e652840d',
               'a8b7eb25',
               'dacd011d',
               '9d05aa60',
               '6e11e6e4',
               '880f1546',
               'f2f7a33e']),
             ('C40', ['2315719c', '9662578f']),
             ('C41', ['34c3c947']),
             ('C42', ['2315719c']),
             ('C43', ['2315719c']),
             ('C44', ['2315719c']),
             ('C45', ['b9ad2acd']),
             ('C46', ['2315719c']),
             ('C47', ['af3e90b7']),
             ('C48',
              ['a8fe4c40',
               '3d4745aa',
               'ff66fa28',
               '008711f0',
               '4e1116fc',
               'bd6d10df',
               '16a3cef8',
               'fbf91a5a',
               '835c1551',
               'bfa8aa39',
               '2b2726f3',
               'e72b9d1c',
               '41f5477e',
               '877055b5',
               'd4c8f7e8',
               '5d8891b0',
               'f3f66216',
               'a26fdf53',
               'e7e9bfba',
               '9b93c8b1',
               'e9da6206',
               '34b6e188',
               'e24059ac']),
             ('C49', ['1bb03c69', '87f7fc87', 'f5aa81fa', 'cd05ca84']),
             ('C50', ['09789b2b']),
             ('C51', ['c89a99ae']),
             ('C52', ['25be66dc']),
             ('C53', ['85d6aca3']),
             ('C54', ['6a2a0c25'])])

In [10]:
l = []
for index,row in Thunderbird_log.iterrows():
    l.append(com_Event_dict[row['Component']].index(row['EventId']))
Thunderbird_log["id"] = l

In [11]:
Thunderbird_log.drop(labels=['Date','Time','PID','User','Month','Day','Location','PID','ParameterList','Timestamp','Content'],axis=1, inplace=True)
Thunderbird_log

,LineId,Label,Component,EventId,EventTemplate,Key,id
0,600001,-,C1,f29fb486,THH(1): <*> <*> Device in FATAL state,E52,0
1,600002,-,C1,f29fb486,THH(1): <*> <*> Device in FATAL state,E52,0
2,600003,"""-",C1,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
3,600004,"""-",C1,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
4,600005,"""VAPI",C1,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2
...,...,...,...,...,...,...,...
399526,999527,"""-",C1,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
399527,999528,"""VAPI",C1,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2
399528,999529,"""VAPI",C1,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2
399529,999530,"""-",C1,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
399530,999531,"""VAPI",C1,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2

In [12]:
EventId_dict = dict(zip(Thunderbird_log['EventId'],Thunderbird_log['id']))
EventId_dict

{'f29fb486': 0,
 'afa7654c': 1,
 '4f5b9781': 2,
 'ef226888': 0,
 '5d37b30c': 0,
 '8e6e114b': 1,
 '7861dafa': 2,
 '51a56721': 3,
 '0170c871': 4,
 '6391d957': 0,
 '7af5f6c5': 0,
 '5f6a681c': 0,
 'b523b147': 5,
 'a0939195': 6,
 '8d134961': 7,
 '5b2bcc81': 1,
 '50345058': 0,
 '09789b2b': 0,
 '5947eee3': 0,
 '27624832': 1,
 'f4455acc': 0,
 'd0052946': 1,
 '3b327ac5': 2,
 'a82970ae': 3,
 'e8b0f746': 4,
 'fe7d0745': 5,
 'f8c00723': 0,
 '182a3d2f': 0,
 '910e288d': 0,
 'b10a98bd': 1,
 '2315719c': 0,
 '45d319cb': 3,
 'a1cbc82b': 4,
 'a20abb3d': 5,
 '6dc36b09': 6,
 'b6bf46de': 7,
 '0f5f997d': 8,
 'a4ff4c6f': 9,
 'f69dda74': 10,
 'ad416b7e': 11,
 'af614352': 12,
 '87cf408f': 13,
 '71357687': 14,
 '115635d6': 15,
 '295c8236': 16,
 '6204d307': 17,
 '8c537990': 18,
 'f3baae88': 19,
 '7e2eac94': 20,
 'de6cd9cf': 21,
 '6d58ac7e': 22,
 'c36d1d3d': 23,
 '1d743fc4': 24,
 '7d2f04f5': 25,
 'cc2cb575': 26,
 'c1a59557': 27,
 '5f45a05e': 28,
 'cd56675f': 29,
 '2fec979e': 30,
 'ab8e12aa': 31,
 '1cf019dc': 32,
 'e727dd7e': 33,
 'f0988321': 34,
 '1ce35610': 35,
 'befec666': 36,
 '5af5972d': 37,
 'cb918ea9': 0,
 '21e60650': 39,
 '6dae5f8b': 40,
 'a6c81dd8': 41,
 '4b27a725': 42,
 '393e6aaa': 43,
 '158c34d8': 44,
 '426f668c': 45,
 '7e9e0987': 46,
 '40014f29': 47,
 'be631275': 48,
 'cd364792': 49,
 '4018d47d': 50,
 'f05494ed': 51,
 '41ffccb1': 52,
 'f7dc852a': 53,
 '2393c4e5': 54,
 'c548107e': 55,
 'abd14c95': 0,
 '6f97e9d4': 0,
 '226c1616': 56,
 'eda996fc': 57,
 '2a1f7496': 58,
 '4c266658': 59,
 'dc008d73': 60,
 '503eca1e': 61,
 '5f59c0fe': 62,
 '61080331': 63,
 '1d6c9690': 64,
 'b218fa4c': 65,
 'da8564c1': 66,
 '3c9bd707': 67,
 '0ccf363e': 68,
 '0ba4f522': 69,
 '154e9fae': 70,
 'b1ecff3c': 71,
 '2d9fabff': 72,
 '0278a557': 73,
 '06825620': 74,
 '8f43df13': 75,
 '4e856061': 76,
 'aebadbc0': 77,
 'cc6328c4': 78,
 '8f61471d': 79,
 '83fe54c5': 80,
 'e29b6981': 81,
 '679e773a': 82,
 'edb20730': 83,
 'a090a511': 84,
 'aff64990': 85,
 '7c4a740d': 86,
 '56824959': 87,
 '415ce39a': 88,
 'f70a10ee': 89,
 '09cd9ade': 90,
 'bdb7ce49': 91,
 '707f0b33': 92,
 'e6f56863': 93,
 '6df6ed98': 94,
 '91e8ab9e': 95,
 '2b566107': 96,
 '3637fd61': 97,
 '02604bb0': 98,
 'd8cdb7cf': 99,
 '50e8fc89': 100,
 '634ae816': 101,
 '4347d6c6': 102,
 '4af88f8f': 103,
 '8d630a2b': 104,
 'f0a878f0': 105,
 'f73595e3': 106,
 '41ed2983': 107,
 '02b10438': 108,
 '4aacee6a': 109,
 '657892af': 110,
 '607eef3d': 111,
 '53f8734e': 112,
 '204ba6f2': 113,
 'b0ef9ace': 114,
 '13c67684': 115,
 '208b1922': 116,
 'cecc13aa': 117,
 'ebb6db13': 118,
 'ee2ae22f': 119,
 '96420960': 120,
 '892c3001': 121,
 '00bc9d8a': 122,
 'bf263f16': 123,
 'a3c4dedb': 124,
 '4768ff86': 125,
 '11e22d59': 126,
 'a3bd2f17': 127,
 '7ccebfbe': 128,
 '866670b9': 129,
 'dbcb1718': 130,
 'cb45fbbf': 131,
 '65e052ed': 132,
 '4b7e6959': 133,
 '6550622f': 134,
 '521066c3': 135,
 'e8438cc2': 136,
 '88474e9c': 137,
 '385a86d9': 138,
 'fe847c07': 139,
 '975383bf': 140,
 '6e3475e7': 141,
 '14d68ea0': 142,
 'e24fae92': 143,
 '3cea1e5a': 144,
 '92398283': 145,
 'ef476468': 146,
 'fe1ca4c4': 147,
 'ed2d7b9b': 148,
 '5ab7d0e6': 149,
 'a166300a': 150,
 '756b90dd': 151,
 'b79529df': 152,
 'eb9b1482': 153,
 '204c3170': 154,
 '14adadc3': 155,
 'cb46a609': 156,
 '71372c58': 157,
 '38fe4fa3': 158,
 'b5e84bfb': 159,
 '323c0b75': 160,
 '69ea804c': 161,
 '3b85d690': 162,
 '337ed584': 163,
 '5de8e064': 164,
 '28d86c57': 165,
 '16f3e1f5': 166,
 'e80c8a5c': 167,
 '2d63468e': 168,
 '9cce776b': 169,
 '8f4c17d6': 170,
 'd7c85960': 171,
 '1c5e39cb': 172,
 '7238147a': 173,
 '90ea87d9': 174,
 'ed48f744': 175,
 '519a6e46': 176,
 '2526593d': 177,
 '69092dfc': 178,
 '72fc5a1c': 179,
 'e8c5a3ff': 180,
 'e2c5eb70': 181,
 '30d35175': 182,
 'f1205e3c': 183,
 'ea2ebcf2': 0,
 '268e6e9a': 0,
 '1a2ac521': 0,
 '144d91a4': 0,
 '9efabb2d': 0,
 '8bf43913': 0,
 '3eb304b6': 1,
 '696dbc03': 2,
 '3a7c1c2f': 3,
 '68afa78e': 0,
 '14930dc8': 184,
 '0bd88115': 0,
 'b95b0ee2': 1,
 '8f9476cd': 1,
 '0fb7ec34': 2,
 '5bca1be3': 3,
 'f9edea77': 0,
 'a84c7411': 9,
 '5067ee0f': 0,
 'ea0f0cf9': 1,
 'f68465f1': 2,
 'ce6689c4': 3,
 '7cffd2ab': 4,
 '50d5309e': 5,
 'f7aa7a98': 7,
 '438072cf': 8,
 'b533c717': 10,
 '337ec120': 0,
 '3adcc40c': 1,
 '143fc45a': 2,
 'a4657e66': 3,
 '3e5fb2d5': 4,
 '3425827a': 5,
 'bacffe20': 6,
 'b73df3e2': 7,
 '684602dc': 8,
 '34111b96': 0,
 '172d92d2': 1,
 'd7b61992': 2,
 '5bba403d': 3,
 'dc4a9fc8': 4,
 '87d982c0': 5,
 '7eccf143': 6,
 '87c67553': 7,
 'af74229d': 8,
 'beb2ace4': 9,
 '22a97846': 0,
 '04b50848': 0,
 '3780647e': 2,
 'ed4394f9': 1,
 'a69485db': 2,
 '54ffff38': 3,
 '26096bac': 185,
 '1da5319d': 186,
 '9b1751bd': 1,
 'e652840d': 1,
 'a8b7eb25': 2,
 '73032e3b': 2,
 '9eb8e3c7': 3,
 '49f6bba5': 4,
 '6208f537': 5,
 'd6087b0c': 2,
 '713e618e': 2,
 '09487f02': 3,
 '12c0517e': 4,
 '99132f5d': 5,
 '14b78a6b': 6,
 '5ba16b80': 7,
 '34c3c947': 0,
 '09d8601c': 3,
 'ff0546a4': 4,
 'fadd4d28': 1,
 'b9ad2acd': 0,
 '99659397': 2,
 'bc4872ea': 3,
 'b4a1b6c7': 187,
 'af3e90b7': 0,
 'b1402c3a': 1,
 'a8fe4c40': 0,
 '3d4745aa': 1,
 'ff66fa28': 2,
 '008711f0': 3,
 '4e1116fc': 4,
 '1bb03c69': 0,
 '87f7fc87': 1,
 'f0c4672c': 188,
 'bd6d10df': 5,
 '47adbf55': 2,
 'c28f47dc': 2,
 '16a3cef8': 6,
 'fbf91a5a': 7,
 '835c1551': 8,
 'bfa8aa39': 9,
 '2b2726f3': 10,
 'e72b9d1c': 11,
 'dacd011d': 3,
 '41f5477e': 12,
 '877055b5': 13,
 'd4c8f7e8': 14,
 '5d8891b0': 15,
 'f5aa81fa': 2,
 '9662578f': 1,
 'f3f66216': 16,
 'a26fdf53': 17,
 'e7e9bfba': 18,
 '55ab9c77': 8,
 '26e04130': 189,
 '7b1c71f5': 190,
 'b7307c84': 9,
 'cd05ca84': 3,
 '9b93c8b1': 19,
 'e9da6206': 20,
 '34b6e188': 21,
 'e24059ac': 22,
 'c89a99ae': 0,
 '1d72dbe7': 8,
 '3e37be4e': 9,
 'd313251e': 10,
 '25be66dc': 0,
 'e88b3270': 2,
 'fad40d5e': 11,
 '436ae99e': 9,
 'a0464834': 10,
 '9e04d0e1': 191,
 '9e54b051': 192,
 '372e7234': 193,
 'b422c811': 194,
 '42d059a0': 195,
 '23c2de50': 196,
 'd4273323': 197,
 'f67f0ac3': 11,
 '31d3084a': 12,
 'cc6bd0df': 13,
 'cd25cf18': 198,
 '12e96422': 14,
 '81311be0': 199,
 'd3809c1a': 200,
 'db3a1891': 201,
 'c7ce01a8': 6,
 'c6a2d330': 202,
 '23684e20': 203,
 '4d20657c': 5,
 '85d6aca3': 0,
 '9d05aa60': 4,
 '6e11e6e4': 5,
 '880f1546': 6,
 'f2f7a33e': 7,
 '6a2a0c25': 0,
 'c49e7242': 204,
 '24bc2b8c': 4,
 'f5db9ad3': 5,
 'b5547c6f': 1,
 '27c493db': 205,
 'f9423625': 3}

In [13]:
Thunderbird_log['EventId'] = Thunderbird_log['EventId'].apply( lambda x: EventId_dict[x])
Thunderbird_log

,LineId,Label,Component,EventId,EventTemplate,Key,id
0,600001,-,C1,0,THH(1): <*> <*> Device in FATAL state,E52,0
1,600002,-,C1,0,THH(1): <*> <*> Device in FATAL state,E52,0
2,600003,"""-",C1,1,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
3,600004,"""-",C1,1,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
4,600005,"""VAPI",C1,2,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2
...,...,...,...,...,...,...,...
399526,999527,"""-",C1,1,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
399527,999528,"""VAPI",C1,2,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2
399528,999529,"""VAPI",C1,2,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2
399529,999530,"""-",C1,1,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,E395,1
399530,999531,"""VAPI",C1,2,"<*> <*> failed, return code = -254 (Fatal erro...",E367,2

In [14]:
Event

,LineId,Label,Timestamp,Date,User,Month,Day,Time,Location,Component,PID,Content,EventId,EventTemplate,ParameterList,Key
0,600001,-,1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,THH(1): mnt_projects/sysapps/src/ib/topspin/to...,f29fb486,THH(1): <*> <*> Device in FATAL state,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E52
2,600003,"""-",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,[KERNEL_IB][ib_mad_dispatch][/mnt_projects/sys...,afa7654c,[KERNEL_IB][ib_mad_dispatch][/<*>-<*>-16/ib/ts...,['mnt_projects/sysapps/src/ib/topspin/topspin-...,E395
4,600005,"""VAPI",1131904443,2005.11.13,an416,Nov,13,09:54:03,an416/an416,C1,NaN,[KERNEL_IB][tsIbTavorMadProcess][/mnt_projects...,4f5b9781,"<*> <*> failed, return code = -254 (Fatal erro...",['[KERNEL_IB][tsIbTavorMadProcess][/mnt_projec...,E367
10,600011,"""-",1131904443,2005.11.13,dn25,Nov,13,09:54:03,dn25/dn25,C2,2260.0,"synchronized to 10.100.28.250, stratum 3""",ef226888,synchronized to <*> stratum <*>,"['10.100.28.250,', '3""']",E44
24,600025,-,1131904444,2005.11.13,tbird-sm1,Nov,13,09:54:04,src@tbird-sm1,C3,24904.0,[INFO]: Configuration caused by some ports in ...,5d37b30c,[INFO]: Configuration caused by some ports in ...,[],E375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315666,915667,-,1131951605,2005.11.13,bn575,Nov,13,23:00:05,bn575/bn575,C26,NaN,[/sbin/fsck.ext3 (1) -- /var],24bc2b8c,[/sbin/fsck.ext3 (1) -- <*>,['/var]'],E407
315667,915668,-,1131951605,2005.11.13,bn575,Nov,13,23:00:05,bn575/bn575,C26,NaN,fsck.ext3 -a /dev/sda5,f5db9ad3,fsck.ext3 -a <*>,['/dev/sda5'],E408
331143,931144,-,1131953731,2005.11.13,bn575,Nov,13,23:35:31,bn575/bn575,C25,NaN,Mon Nov 14 00:35:16 MST 2005,b5547c6f,Mon Nov 14 <*> MST 2005,['00:35:16'],E14
336911,936912,-,1131954540,2005.11.13,#1#,Nov,13,23:49:00,#1#/#1#,C1,NaN,audit(1131950940.033:0): avc: denied { search ...,27c493db,audit(<*><*>): avc: denied { search } for pid<...,"['1131950940.033:0', '=19258', '=30 scontext=u...",E402
342537,942538,-,1131955321,2005.11.14,#21#,Nov,14,00:02:01,#21#/#21#,C9,26273.0,(#65#) CMD (/home/#65#/salinas/tbird/cron_scri...,f9423625,(#65#) CMD (/home/#65#/salinas/tbird/cron_scri...,[],E477

In [15]:
Thunderbird_log["EventTemplate"] = Thunderbird_log["EventTemplate"].map(lambda x: re.sub("[<*>/:]","",x))
Thunderbird_log["EventTemplate"] = Thunderbird_log["EventTemplate"].map(lambda x: "[CLS] " + x + " [SEP]")
Thunderbird_log

,LineId,Label,Component,EventId,EventTemplate,Key,id
0,600001,-,C1,0,[CLS] THH(1) Device in FATAL state [SEP],E52,0
1,600002,-,C1,0,[CLS] THH(1) Device in FATAL state [SEP],E52,0
2,600003,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
3,600004,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
4,600005,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2
...,...,...,...,...,...,...,...
399526,999527,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
399527,999528,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2
399528,999529,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2
399529,999530,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
399530,999531,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2

In [16]:
from transformers import logging
from transformers import BertModel, BertTokenizer
logging.set_verbosity_warning()
model = BertModel.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [17]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [18]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (2): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (3): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (4): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (5): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (6): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (7): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (8): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (9): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (10): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (11): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [19]:
def sent_to_vec(sent, tokenizer, model, pooling, max_length):
    with torch.no_grad():
        inputs = tokenizer(sent, return_tensors="pt", padding=True, truncation=True,  max_length=max_length)
        inputs['input_ids'] = inputs['input_ids'].to(device)
        inputs['token_type_ids'] = inputs['token_type_ids'].to(device)
        inputs['attention_mask'] = inputs['attention_mask'].to(device)

        hidden_states = model(**inputs, return_dict=True, output_hidden_states=True).hidden_states
        output_hidden_state = (hidden_states[-1] + hidden_states[1]).mean(dim=1)
        vec = output_hidden_state.cpu().numpy()[0]
    return vec

In [20]:
def sents_to_vecs(sents, tokenizer, model, pooling, max_length, verbose=True):
    vecs = []
    if verbose:
        sents = tqdm(sents)
    for sent in sents:
        vec = sent_to_vec(sent, tokenizer, model, pooling, max_length)
        vecs.append(vec)
    assert len(sents) == len(vecs)
    vecs = np.array(vecs)
    return vecs

In [21]:
def compute_kernel_bias(vecs):
    """计算kernel和bias
    最后的变换：y = (x + bias).dot(kernel)
    """
    mu = vecs.mean(axis=0, keepdims=True)#(1, 768) 求各列的均值
    cov = np.cov(vecs.T) #(768,768)计算每个特征维度之间的协方差
    u, s, vh = np.linalg.svd(cov) #进行奇异值分解
    W_inv = np.dot(u, np.diag(s**0.5)) 
    W = np.linalg.inv(W_inv.T)
    return W[:, :256], -mu

In [22]:
def transform_and_normalize(vecs, kernel=None, bias=None):
    """应用变换，然后标准化
    """
    if not (kernel is None or bias is None):
        vecs = (vecs + bias).dot(kernel)
    return vecs / (vecs**2).sum(axis=1, keepdims=True)**0.5

In [23]:
EventTemplate = Event['EventTemplate']

In [ ]:
from tqdm import tqdm
data_vec = sents_to_vecs(EventTemplate, tokenizer, model, 'first_last_avg', 64)

 61%|█████████████████████████████████████████████████▏                              | 226/368 [00:09<00:05, 24.69it/s]

In [ ]:
kernel, bias = compute_kernel_bias(data_vec)

In [45]:
load_dict = np.load('com_encode_dict256tb.npy',allow_pickle=True).item()

In [142]:
Thunderbird_log

,LineId,Label,Component,EventId,EventTemplate,Key,id
0,600001,-,C1,0,[CLS] THH(1) Device in FATAL state [SEP],E52,0
1,600002,-,C1,0,[CLS] THH(1) Device in FATAL state [SEP],E52,0
2,600003,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
3,600004,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
4,600005,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2
...,...,...,...,...,...,...,...
399526,999527,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
399527,999528,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2
399528,999529,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2
399529,999530,"""-",C1,1,[CLS] [KERNEL_IB][ib_mad_dispatch][--16ibts_ap...,E395,1
399530,999531,"""VAPI",C1,2,"[CLS] failed, return code = -254 (Fatal erro...",E367,2

In [143]:
log_data = []
sequence_len=20
for i in range(0,len(Thunderbird_log)-sequence_len,10):
    log_data.append(Thunderbird_log['EventId'][i:i+sequence_len])
reshaped_logs = np.array(log_data).astype('float64')
reshaped_log=[]
for i in range(len(reshaped_logs)):
    reshaped_log.append(list(map(int,reshaped_logs[i])))
reshaped_log

[[0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1],
 [0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, 1, 1, 1, 2, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2],
 [2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 0, 0],
 [2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 2, 2],
 [5, 6, 7, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1],
 [0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2],
 [1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2],
 [2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2],
 [2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0],
 [2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1],
 [0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 1, 1],
 [2, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2],
 [1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3],
 [0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 0, 1],
 [3, 4, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0],
 [1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7],
 [0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2],
 [0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2],
 [2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3],
 [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 1],
 [3, 3, 4, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0],
 [1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 1, 0, 0, 0, 0, 1],
 [0, 5, 6, 7, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2],
 [1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2],
 [0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1],
 [0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1],
 [1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0],
 [2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 1],
 [6, 7, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1],
 [1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2],
 [1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3],
 [2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 1],
 [3, 3, 4, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0],
 [1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 1, 1],
 [0, 0, 0, 5, 6, 7, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 0, 0],
 [2, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1],
 [0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3],
 [2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 0],
 [3, 3, 4, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 0],
 [1, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 1, 1],
 [0, 5, 6, 7, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0],
 [2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0],
 [0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1],
 [1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1],
 [2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0],
 [1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 1, 2],
 [5, 6, 7, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 1, 2],
 [2, 2, 0, 0, 1, 1, 2, 2, 1, 2, 3, 0, 0, 1, 1, 2, 2, 0, 0, 0],
 [3, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 3],
 [1, 1, 2, 2, 0, 1, 1, 2, 2, 3, 3, 4, 0, 1, 2, 0, 1, 1, 2, 2],
 [3, 4, 0, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1],
 [0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 1],
 [2, 2, 0, 0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2],
 [1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2],
 [2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2],
 [2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0],
 [0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 1, 1],
 [0, 0, 0, 5, 6, 7, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 0, 0],
 [2, 2, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1],
 [1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2],
 [2, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1],
 [2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0],
 [2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 1, 2, 0, 0, 1],
 [5, 6, 7, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2],
 [2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 1],
 [2, 2, 0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0],
 [1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2],
 [1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 1, 1],
 [0, 5, 6, 7, 0, 0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 2, 2],
 [2, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 0],
 [0, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1],
 [0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2],
 [1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0],
 [0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0],
 [0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0],
 [1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0],
 [0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0],
 [1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3],
 [0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 1, 1, 2],
 [4, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0],
 [0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 1, 1, 2, 2, 0, 1, 2, 0, 0, 1],
 [1, 1, 2, 2, 0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2],
 [1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3],
 [2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0],
 [3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0],
 [1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 1, 1],
 [5, 6, 7, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0],
 [2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 1],
 [0, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 1, 1, 2],
 [1, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2],
 [2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0],
 [0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0],
 [0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0],
 [1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 1],
 [0, 1, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 1, 1, 2],
 [1, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2],
 [2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0],
 [2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 2],
 [0, 0, 5, 6, 7, 0, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 1, 1, 2],
 [0, 0, 1, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0],
 [2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3],
 [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0],
 [3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0],
 [0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 1, 1, 2, 2],
 [6, 7, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, 2],
 [0, 0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0],
 [0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3],
 [0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 1, 1, 2],
 [4, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 2, 0, 0],
 [5, 6, 7, 0, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 2, 2],
 [1, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 1, 1],
 [2, 0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0],
 [1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2],
 [1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0],
 [2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0],
 [0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2],
 [1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2],
 [1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3],
 [0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 1, 1, 2, 2, 0],
 [3, 4, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6],
 [0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 1, 1, 2, 2, 0, 0, 1],
 [7, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0],
 [2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1],
 [0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0],
 [1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2],
 [0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 1, 1],
 [0, 5, 6, 7, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0],
 [2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1],
 [0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 1, 2],
 [1, 2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2],
 [2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0],
 [2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1],
 [0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1],
 [1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0],
 [1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3],
 [0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0],
 [3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0],
 [1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 0, 1],
 [5, 6, 7, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2],
 [1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2],
 [0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1],
 [2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1],
 [1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0],
 [2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 2, 2],
 [5, 6, 7, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1],
 [0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1],
 [1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3],
 [2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 1, 1, 2, 2],
 [3, 3, 4, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0],
 [0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 1, 2, 2, 0, 0, 1, 2],
 [0, 0, 0, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 0],
 [0, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1],
 [0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0],
 [1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0],
 [1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 5, 6, 7, 0, 0],
 [1, 0, 0, 0, 0, 5, 6, 7, 0, 0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 0],
 [1, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0],
 [0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 2, 2],
 [1, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 1],
 [2, 3, 3, 3, 4, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0],
 [2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 3, 3, 4, 5, 0, 3, 0],
 [0, 1, 2, 3, 3, 4, 5, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6],
 [0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 2, 2, 0, 0],
 [7, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 0],
 [1, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0],
 [0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3],
 [0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 1, 1],
 [4, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0],
 [2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 2, 2, 0],
 [6, 7, 0, 0, 0, 1, 1, 2, 2, 0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 0],
 [1, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2],
 [0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2],
 [2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2],
 [2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1],
 [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1],
 [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 1, 1],
 [0, 0, 5, 6, 7, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1],
 [2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0],
 [2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4],
 [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1],
 [0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0],
 [2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 5, 6, 6],
 [0, 0, 0, 0, 0, 3, 4, 5, 6, 6, 7, 8, 8, 8, 8, 8, 6, 9, 9, 9],
 [7, 8, 8, 8, 8, 8, 6, 9, 9, 9, 10, 11, 11, 12, 12, 12, 13, 13, 13, 14],
 [10,
  11,
  11,
  12,
  12,
  12,
  13,
  13,
  13,
  14,
  14,
  14,
  14,
  15,
  15,
  15,
  15,
  16,
  9,
  9],
 [14, 14, 14, 15, 15, 15, 15, 16, 9, 9, 17, 9, 9, 18, 19, 20, 21, 22, 23, 24],
 [17,
  9,
  9,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  31,
  31,
  32],
 [25,
  26,
  27,
  28,
  29,
  30,
  31,
  31,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  0,
  39,
  40,
  41,
  42],
 [33,
  34,
  35,
  36,
  37,
  0,
  39,
  40,
  41,
  42,
  43,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  50],
 [43, 43, 44, 45, 46, 47, 48, 49, 50, 50, 51, 52, 53, 54, 55, 0, 0, 0, 0, 0],
 [51, 52, 53, 54, 55, 0, 0, 0, 0, 0, 56, 57, 57, 58, 59, 60, 61, 62, 63, 64],
 [56,
  57,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  69,
  68,
  70,
  70,
  70],
 [65,
  66,
  67,
  68,
  69,
  69,
  68,
  70,
  70,
  70,
  69,
  71,
  71,
  71,
  71,
  71,
  71,
  71,
  71,
  71],
 [69,
  71,
  71,
  71,
  71,
  71,
  71,
  71,
  71,
  71,
  71,
  72,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73],
 [71,
  72,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73],
 [73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  73,
  74,
  75,
  75,
  76,
  77,
  78,
  79],
 [73,
  73,
  73,
  74,
  75,
  75,
  76,
  77,
  78,
  79,
  80,
  80,
  81,
  82,
  83,
  84,
  84,
  84,
  22,
  22],
 [80,
  80,
  81,
  82,
  83,
  84,
  84,
  84,
  22,
  22,
  23,
  23,
  24,
  85,
  86,
  87,
  88,
  88,
  88,
  88],
 [23,
  23,
  24,
  85,
  86,
  87,
  88,
  88,
  88,
  88,
  89,
  90,
  90,
  90,
  90,
  91,
  92,
  93,
  94,
  95],
 [89,
  90,
  90,
  90,
  90,
  91,
  92,
  93,
  94,
  95,
  32,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  103],
 [32,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  103,
  103,
  103,
  103,
  104,
  105,
  106,
  107,
  107,
  107,
  107],
 [103,
  103,
  103,
  104,
  105,
  106,
  107,
  107,
  107,
  107,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  113,
  113,
  113],
 [107,
  108,
  109,
  110,
  111,
  112,
  113,
  113,
  113,
  113,
  113,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  119,
  120],
 [113,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130],
 [121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  137,
  137,
  137],
 [131,
  132,
  133,
  134,
  135,
  136,
  137,
  137,
  137,
  137,
  138,
  139,
  140,
  141,
  140,
  142,
  143,
  144,
  145,
  146],
 [138,
  139,
  140,
  141,
  140,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  147,
  148,
  147,
  148,
  147,
  148,
  147,
  148],
 [147,
  148,
  147,
  148,
  147,
  148,
  147,
  148,
  147,
  148,
  149,
  150,
  150,
  151,
  152,
  153,
  154,
  154,
  154,
  155],
 [149,
  150,
  150,
  151,
  152,
  153,
  154,
  154,
  154,
  155,
  155,
  155,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162],
 [155,
  155,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172],
 [163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181],
 [173,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  179,
  180,
  181,
  179,
  180,
  181,
  182,
  183,
  183,
  183],
 [179,
  180,
  181,
  179,
  180,
  181,
  182,
  183,
  183,
  183,
  183,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0],
 [183, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 2, 3, 3, 3, 3, 0, 184, 0, 0],
 [1, 2, 3, 3, 3, 3, 0, 184, 0, 0, 1, 0, 1, 2, 3, 0, 0, 0, 0, 9],
 [1, 0, 1, 2, 3, 0, 0, 0, 0, 9, 0, 1, 2, 3, 4, 5, 0, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 0, 7, 8, 9, 10, 0, 0, 1, 2, 3, 4, 5, 6, 7],
 [10, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 1, 1, 2, 2, 2, 2],
 [8, 0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7],
 [3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 7, 7, 9, 9, 9, 9, 9, 9],
 [8, 8, 7, 7, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 0, 2, 0, 5],
 [9, 9, 0, 0, 0, 0, 0, 2, 0, 5, 6, 7, 1, 0, 0, 0, 0, 1, 1, 2],
 [6, 7, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 0, 0],
 [2, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0],
 [0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 1],
 [0, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1],
 [1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 1, 1, 2, 0, 0, 2, 3, 0],
 [2, 0, 1, 1, 2, 0, 0, 2, 3, 0, 0, 0, 185, 186, 103, 138, 0, 0, 0, 154],
 [0, 0, 185, 186, 103, 138, 0, 0, 0, 154, 1, 1, 2, 0, 2, 2, 2, 2, 2, 2],
 [1, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4],
 [3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 0, 0],
 [4, 4, 4, 4, 4, 4, 4, 5, 0, 0, 0, 2, 0, 1, 2, 3, 3, 3, 3, 3],
 [0, 2, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0],
 [4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 3, 4, 1, 0, 0, 0, 0, 0, 1, 2],
 [3, 4, 1, 0, 0, 0, 0, 0, 1, 2, 3, 1, 1, 1, 1, 0, 0, 1, 2, 3],
 [3, 1, 1, 1, 1, 0, 0, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 0],
 [1, 2, 3, 1, 2, 3, 1, 2, 3, 0, 5, 6, 7, 0, 0, 0, 0, 1, 1, 2],
 [5, 6, 7, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 1, 1, 2, 2],
 [2, 0, 0, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 187],

In [157]:
com_data = []
sequence_len=20
for j in range(0,len(Thunderbird_log)-sequence_len,10):
    com_data.append(Thunderbird_log['Component'][j:j+sequence_len])
reshaped_com = np.array(com_data).astype('str')
reshaped_com[0:10]

array([['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C2',
        'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
       ['C2', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1',
        'C1', 'C1', 'C2', 'C3', 'C3', 'C3', 'C3', 'C3', 'C3'],
       ['C1', 'C1', 'C1', 'C2', 'C3', 'C3', 'C3', 'C3', 'C3', 'C3', 'C3',
        'C3', 'C3', 'C3', 'C3', 'C1', 'C1', 'C1', 'C1', 'C1'],
       ['C3', 'C3', 'C3', 'C3', 'C3', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1',
        'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C4', 'C4'],
       ['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C4', 'C4', 'C4',
        'C4', 'C4', 'C4', 'C4', 'C4', 'C4', 'C4', 'C2', 'C5'],
       ['C4', 'C4', 'C4', 'C4', 'C4', 'C4', 'C4', 'C4', 'C2', 'C5', 'C6',
        'C2', 'C2', 'C4', 'C4', 'C4', 'C4', 'C4', 'C2', 'C4'],
       ['C6', 'C2', 'C2', 'C4', 'C4', 'C4', 'C4', 'C4', 'C2', 'C4', 'C3',
        'C3', 'C3', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
       ['C3', 'C3', 'C3', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1',
        'C1', 'C1', 'C1', 'C2', 'C2', 'C2', 'C1', 'C1', 'C1'],
       ['C1', 'C1', 'C1', 'C1', 'C2', 'C2', 'C2', 'C1', 'C1', 'C1', 'C1',
        'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
       ['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1',
        'C5', 'C6', 'C2', 'C4', 'C3', 'C3', 'C3', 'C3', 'C3']],
      dtype='<U3')

In [106]:
# log_label = []
# for k in range(0,len(Thunderbird_log)-sequence_len,10):
#     log_label.append(Thunderbird_log['Label'][i:i+sequence_len])
# reshaped_label = np.array(log_label).astype('str')
# print(reshaped_label)
# label=[]
# for i in range(len(reshaped_label)):
#      for j in range(len(reshaped_label[i])):
#             if reshaped_label[i][j]=='"VAPI':
#                 label.append(1)
#                 break
#             else:
#                 label.append(0)
# a=0
# for i in range(len(label)):
#     if label[i]==0:
#         a = a+1

# print(a)

[['"VAPI' '-' '-' ... '-' '-' '-']
 ['"VAPI' '-' '-' ... '-' '-' '-']
 ['"VAPI' '-' '-' ... '-' '-' '-']
 ...
 ['"VAPI' '-' '-' ... '-' '-' '-']
 ['"VAPI' '-' '-' ... '-' '-' '-']
 ['"VAPI' '-' '-' ... '-' '-' '-']]

In [73]:
# reshaped_label=lambda x:1 if reshaped_label[x]=='"VAPI' else 0
# reshaped_label

In [152]:
# reshaped_log=reshaped_log.tolist()
# data_dict = pd.DataFrame()
s=pd.Series(reshaped_log)
s

0        [0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, ...
1        [0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, ...
2        [2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, ...
3        [2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...
4        [2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, ...
                               ...
39947    [0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 2, 1, 2, ...
39948    [1, 2, 2, 1, 2, 3, 0, 0, 0, 0, 1, 1, 1, 2, 2, ...
39949    [1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...
39950    [2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, ...
39951    [0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 0, ...
Length: 39952, dtype: object

In [151]:
# reshaped_com=reshaped_com.tolist()
df_dict = pd.DataFrame(s, columns=['EventSequence'])
df_dict['Component']=reshaped_com
df_dict

,EventSequence,Component
0,"[0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, ...","[C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C2, C..."
1,"[0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, ...","[C2, C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C..."
2,"[2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, ...","[C1, C1, C1, C2, C3, C3, C3, C3, C3, C3, C3, C..."
3,"[2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...","[C3, C3, C3, C3, C3, C1, C1, C1, C1, C1, C1, C..."
4,"[2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, ...","[C1, C1, C1, C1, C1, C1, C1, C1, C4, C4, C4, C..."
...,...,...
39947,"[0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 2, 1, 2, ...","[C1, C1, C1, C1, C1, C5, C6, C1, C1, C1, C1, C..."
39948,"[1, 2, 2, 1, 2, 3, 0, 0, 0, 0, 1, 1, 1, 2, 2, ...","[C1, C1, C1, C3, C3, C3, C1, C1, C1, C1, C1, C..."
39949,"[1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...","[C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C..."
39950,"[2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, ...","[C1, C1, C1, C1, C1, C1, C1, C2, C4, C4, C3, C..."
39951,"[0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 0, ...","[C3, C3, C3, C3, C3, C3, C3, C3, C3, C3, C3, C..."

In [164]:
log_label = []
for k in range(0,len(Thunderbird_log)-sequence_len,10):
    log_label.append(Thunderbird_log['Label'][k:k+sequence_len])
reshaped_label = np.array(log_label).astype('str')
result_label = []
for m in range(0,len(reshaped_label)):
    if '"VAPI' in reshaped_label[m]:
        result_label.append(1)
    else:
        result_label.append(0)
print(len(result_label))
print(result_label.count(1))
print(result_label.count(0))

# print(reshaped_label[0:10])
# print(Thunderbird_log[0:10])

39952
33885
6067

In [182]:
df_dict['Label']=result_label
df_dict

,EventSequence,Component,Label
0,"[0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
1,"[0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, ...","['C2', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
2,"[2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, ...","['C1', 'C1', 'C1', 'C2', 'C3', 'C3', 'C3', 'C3...",1
3,"[2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...","['C3', 'C3', 'C3', 'C3', 'C3', 'C1', 'C1', 'C1...",1
4,"[2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
...,...,...,...
39947,"[0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 2, 1, 2, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C5', 'C6', 'C1...",1
39948,"[1, 2, 2, 1, 2, 3, 0, 0, 0, 0, 1, 1, 1, 2, 2, ...","['C1', 'C1', 'C1', 'C3', 'C3', 'C3', 'C1', 'C1...",1
39949,"[1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
39950,"[2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C2...",1
39951,"[0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 0, ...","['C3', 'C3', 'C3', 'C3', 'C3', 'C3', 'C3', 'C3...",1

In [183]:
df_dict.to_csv("Thunderbird_C_seq",index=False)

In [184]:
df_dict = pd.read_csv("Thunderbird_C_seq",memory_map=True)
df_dict

,EventSequence,Component,Label
0,"[0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 1, 2, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
1,"[0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, ...","['C2', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
2,"[2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, ...","['C1', 'C1', 'C1', 'C2', 'C3', 'C3', 'C3', 'C3...",1
3,"[2, 3, 3, 3, 4, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...","['C3', 'C3', 'C3', 'C3', 'C3', 'C1', 'C1', 'C1...",1
4,"[2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
...,...,...,...
39947,"[0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 2, 1, 2, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C5', 'C6', 'C1...",1
39948,"[1, 2, 2, 1, 2, 3, 0, 0, 0, 0, 1, 1, 1, 2, 2, ...","['C1', 'C1', 'C1', 'C3', 'C3', 'C3', 'C1', 'C1...",1
39949,"[1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0, 1, 1, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1...",1
39950,"[2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, ...","['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C2...",1
39951,"[0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 1, 2, 0, 0, ...","['C3', 'C3', 'C3', 'C3', 'C3', 'C3', 'C3', 'C3...",1

In [191]:
df_dict["EventSequence"] = df_dict["EventSequence"].map(lambda x: eval(x))

In [193]:
df_dict["Component"] = df_dict["Component"].map(lambda x: eval(x))

In [194]:
for index,row in  df_dict.iterrows():
    for x in range(len(row["EventSequence"])):
        row["EventSequence"][x] = row["EventSequence"][x]+1
    row["EventSequence"].append(0)

In [195]:
for index,row in  df_dict.iterrows():
    row["Component"].append("C0")

In [196]:
df_dict

,EventSequence,Component,Label
0,"[1, 1, 2, 2, 3, 3, 1, 1, 2, 3, 1, 1, 2, 2, 3, ...","[C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C2, C...",1
1,"[1, 1, 2, 2, 3, 3, 1, 1, 2, 2, 3, 3, 3, 1, 1, ...","[C2, C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C...",1
2,"[3, 3, 3, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, ...","[C1, C1, C1, C2, C3, C3, C3, C3, C3, C3, C3, C...",1
3,"[3, 4, 4, 4, 5, 1, 1, 2, 2, 3, 3, 1, 1, 2, 2, ...","[C3, C3, C3, C3, C3, C1, C1, C1, C1, C1, C1, C...",1
4,"[3, 1, 1, 2, 2, 2, 3, 3, 1, 1, 1, 1, 1, 1, 1, ...","[C1, C1, C1, C1, C1, C1, C1, C1, C4, C4, C4, C...",1
...,...,...,...
39947,"[1, 2, 2, 3, 3, 2, 1, 1, 1, 2, 2, 3, 3, 2, 3, ...","[C1, C1, C1, C1, C1, C5, C6, C1, C1, C1, C1, C...",1
39948,"[2, 3, 3, 2, 3, 4, 1, 1, 1, 1, 2, 2, 2, 3, 3, ...","[C1, C1, C1, C3, C3, C3, C1, C1, C1, C1, C1, C...",1
39949,"[2, 2, 2, 3, 3, 3, 1, 2, 2, 3, 3, 1, 1, 2, 2, ...","[C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C1, C...",1
39950,"[3, 1, 1, 2, 2, 3, 3, 1, 1, 1, 1, 2, 2, 2, 3, ...","[C1, C1, C1, C1, C1, C1, C1, C2, C4, C4, C3, C...",1
39951,"[1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 2, 3, 1, 1, ...","[C3, C3, C3, C3, C3, C3, C3, C3, C3, C3, C3, C...",1

In [197]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(df_dict,df_dict["Label"]):
    strat_train_set=df_dict.loc[train_index]
    strat_test_set=df_dict.loc[test_index]
strat_test_set["Label"].value_counts() / len(strat_test_set)# 计算分层抽样后的各个数据占的比例

1    0.848204
0    0.151796
Name: Label, dtype: float64

In [198]:
strat_train_set = df_dict[:33559]
strat_test_set = df_dict[33559:]

In [199]:
strat_test_set.reset_index(drop=True,inplace=True)

In [202]:
from dgl.data import DGLDataset
from dgl.data.utils import save_graphs
class TestDataset(DGLDataset):
    def __init__(self):
        super(TestDataset,self).__init__(name='TestDataset')
    def save(self):
        # save graphs and labels
        graph_path = 'Thunderbird_Test_seq.bin'
        save_graphs(graph_path, self.graphs, {'labels': self.label})
    def process(self):
        node_max = 0
        self.graphs=[]
        data_dict = strat_test_set
        self.label = torch.tensor(data_dict["Label"].values)
        for q in range(data_dict.shape[0]):
            Event = np.array(data_dict['EventSequence'][q])
            Componen = np.array(data_dict['Component'][q])
            graph_1 = {}
            CC = np.unique(Componen)
            for i in CC:
                s = [data_dict['EventSequence'][q][data_dict['Component'][q].index(i)]]
                t = []
                for j in range(data_dict['Component'][q].index(i)+1,len(data_dict['Component'][q])):
                    if data_dict['Component'][q][j] == i:
                        t.append(data_dict['EventSequence'][q][j])
                        s.append(data_dict['EventSequence'][q][j])
                s.pop()
                T = torch.IntTensor(t)
                S = torch.IntTensor(s)
                graph_1[(i, 'con', i)] = (S, T)
            graph_2 = {}
            for i in range(len(data_dict['EventSequence'][q])-1):
                if data_dict['Component'][q][i] != data_dict['Component'][q][i+1]:
                    l = [[data_dict['EventSequence'][q][i]],[data_dict['EventSequence'][q][i+1]]]
                    if (data_dict['Component'][q][i], 'dif', data_dict['Component'][q][i+1]) in graph_2:
                        graph_2[(data_dict['Component'][q][i], 'dif', data_dict['Component'][q][i+1])][0].append(data_dict['EventSequence'][q][i])
                        graph_2[(data_dict['Component'][q][i], 'dif', data_dict['Component'][q][i+1])][1].append(data_dict['EventSequence'][q][i+1])
                    else:
                        graph_2[(data_dict['Component'][q][i], 'dif', data_dict['Component'][q][i+1])] = l
            for key in graph_2:
                S = torch.IntTensor(graph_2[key][0])
                T = torch.IntTensor(graph_2[key][1])
                graph_2[key] = (S, T)
            graph = {}
            graph.update(graph_1) 
            graph.update(graph_2)
            G = dgl.heterograph(graph)
            sum =0
            for x in G.ntypes:
                sum =sum+G.number_of_nodes(x)
            if sum>node_max:
                node_max = sum
            self.graphs.append(G)
        print(node_max)
    def __getitem__(self, idx):
        return self.graphs[idx], self.label[idx]
    def __len__(self):
        return len(self.graphs)

In [203]:
Testdataset = TestDataset()

243

In [204]:
from dgl.data import DGLDataset
from dgl.data.utils import save_graphs
class TrainDataset(DGLDataset):
    def __init__(self):
        super(TrainDataset,self).__init__(name='TrainDataset')
    def save(self):
        # save graphs and labels
        graph_path = 'Thunderbird_Train_seq.bin'
        save_graphs(graph_path, self.graphs, {'labels': self.label})
    def process(self):
        self.graphs=[]
        node_max = 0
        data_df = strat_train_set
        self.label = torch.tensor(data_df["Label"].values)
        for q in range(data_df.shape[0]):
            Event = np.array(data_df['EventSequence'][q])
            Componen = np.array(data_df['Component'][q])
            graph_1 = {}
            CC = np.unique(Componen)
            for i in CC:
                s = [data_df['EventSequence'][q][data_df['Component'][q].index(i)]]
                t = []
                for j in range(data_df['Component'][q].index(i)+1,len(data_df['Component'][q])):
                    if data_df['Component'][q][j] == i:
                        t.append(data_df['EventSequence'][q][j])
                        s.append(data_df['EventSequence'][q][j])
                s.pop()
                T = torch.IntTensor(t)
                S = torch.IntTensor(s)
                graph_1[(i, 'con', i)] = (S, T)
            graph_2 = {}
            for i in range(len(data_df['EventSequence'][q])-1):
                if data_df['Component'][q][i] != data_df['Component'][q][i+1]:
                    l = [[data_df['EventSequence'][q][i]],[data_df['EventSequence'][q][i+1]]]
                    if (data_df['Component'][q][i], 'dif', data_df['Component'][q][i+1]) in graph_2:
                        graph_2[(data_df['Component'][q][i], 'dif', data_df['Component'][q][i+1])][0].append(data_df['EventSequence'][q][i])
                        graph_2[(data_df['Component'][q][i], 'dif', data_df['Component'][q][i+1])][1].append(data_df['EventSequence'][q][i+1])
                    else:
                        graph_2[(data_df['Component'][q][i], 'dif', data_df['Component'][q][i+1])] = l
            for key in graph_2:
                S = torch.IntTensor(graph_2[key][0])
                T = torch.IntTensor(graph_2[key][1])
                graph_2[key] = (S, T)
            graph = {}
            graph.update(graph_1) 
            graph.update(graph_2)
            G = dgl.heterograph(graph)
            sum =0
            for x in G.ntypes:
                sum =sum+G.number_of_nodes(x)
            if sum>node_max:
                node_max = sum
            self.graphs.append(G)
        print(node_max)
    def __getitem__(self, idx):
        return self.graphs[idx], self.label[idx]
    def __len__(self):
        return len(self.graphs)

In [205]:
Traindataset = TrainDataset()

247